# Generated by Django 3.2.8 on 2021-11-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Pictures',
        ),
    ]
