# Generated by Django 3.2.8 on 2021-11-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_auto_20211127_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='category',
            field=models.ManyToManyField(to='galleria.Category'),
        ),
    ]
