# Generated by Django 3.2.8 on 2021-11-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0004_pictures_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='category',
        ),
        migrations.AddField(
            model_name='pictures',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galleria.category'),
        ),
    ]
