# Generated by Django 3.2.8 on 2021-11-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0006_auto_20211128_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
